# frozen_string_literal: true
module DiscourseShorts
  # One-time starter library (already oEmbed-validated). Inserted once, idempotently,
  # so a fresh install ships with a full feed. Admin deletions are respected (the
  # seeded_v1 flag stops it re-adding). Grow beyond this via submissions + ingest.
  module Seeder
    STARTER = [
      ["bUZbW0QQdMQ", "Mobile home reno: before & after", "mobile-home,transformation,renovation"],
      ["xTXGQo6jDAw", "From ruins to a cozy modern home", "transformation,modern,renovation"],
      ["Rwcpl-OKSqc", "Extreme house renovation — day 1", "diy,extreme,renovation"],
      ["LLfQUt1C_Lg", "Top 5 home renovation projects", "tips,projects,renovation"],
      ["Ku3ymDgGqas", "Massive home renovation update", "update,renovation"],
      ["hH3lopgElXs", "This reno is so bad it's funny 🤣", "funny,fail,diy"],
      ["7fKolslGQ4M", "Dream bathroom & kitchen remodel ✨", "kitchen,bathroom,remodel"],
      ["kWjFQdRySQc", "Full house reset: kitchen & bath", "kitchen,bathroom,transformation"],
      ["lToHTjAo5vM", "Modern bathroom oasis remodel", "bathroom,modern,remodel"],
      ["WQeGwIzJy_k", "Stunning full home renovation", "kitchen,bathroom,renovation"],
      ["nH6P_EC4qEg", "Fix & flip kitchen transformation", "kitchen,flip,renovation"],
      ["vAVfYSRyInw", "Stunning bathroom transformation", "bathroom,transformation"],
      ["3c7Uu8QsxR0", "3-day bathroom transformation", "bathroom,transformation,diy"],
      ["iDkZlgMqUzQ", "Small bathroom, big transformation 🛁", "bathroom,diy,carpentry"],
      ["iOWxGfUOoTo", "Satisfying ugly wall demolition", "demolition,satisfying,diy"],
      ["WTub7BFIyVw", "Satisfying ceiling plastering", "drywall,diy,satisfying"],
      ["fgQA22tfDOI", "Insane blue epoxy river floor 🔥", "epoxy,flooring,diy"],
      ["Wtu5-ybHye4", "Muddy mess → backyard oasis ✨", "outdoor,landscaping,transformation"],
      ["1oZnc1kt0sQ", "How to: connect pipe in a tight corner", "plumbing,howto,learn"],
      ["F6e_81WxJEk", "How to secure water pipes at home", "plumbing,howto,learn"],
      ["7HBCi7fcHO4", "Neatly close the end of a pipe", "plumbing,howto,learn"],
      ["KDib0rMx5Cg", "Make a reliable internal pipe plug", "plumbing,howto,learn"],
      ["862zQNi3qbM", "Extract a broken pipe — no special tools", "plumbing,tools,learn"],
      ["V_AoLm28vys", "Tile floor installation tips", "tile,flooring,howto,learn"],
      ["ufkiGwdkcog", "Vertical 12x24 shower wall tile tips", "tile,bathroom,howto,learn"],
      ["0hAclGIjddw", "Wood-look tile: perfect finish", "tile,flooring,howto,learn"],
      ["1EJvCtPGY-0", "Painter's tape tips & tricks", "painting,howto,learn"],
      ["yVGU-Ajh5Dw", "Pro carpenter woodworking tips", "carpentry,howto,learn"],
      ["9yW6zgsZMtw", "Carpentry tips for beginners", "carpentry,diy,learn"],
      ["YIn8hhGLhgc", "Make a perfect wood joint", "carpentry,woodworking,learn"],
      ["N-rpiK-UW-o", "Avoid these renovation mistakes", "tips,mistakes,learn"],
      ["2jSuhWWEh7s", "5 renovation mistakes to avoid", "tips,mistakes,learn"],
      ["FJGFHl04VOA", "Reno mistakes before you sell", "tips,mistakes,learn"],
      ["ESyqAX6Sx1I", "Viral house reno: before & after", "transformation,beforeafter"],
      ["8lbR5aurCQU", "Destroyed room → stunning redo", "transformation,beforeafter"],
      ["ZVsWKIlvmeU", "Turn a wall cabinet into a base cabinet", "cabinets,kitchen,howto,learn"],
      ["ADuAocblU4U", "Install lower cabinets on uneven floors", "cabinets,kitchen,howto,learn"],
      ["EJDAILewmOw", "Space-plug cabinet fixings", "cabinets,kitchen,howto,learn"],
      ["B4M6BTma6eQ", "How to use a cabinet clamp", "cabinets,kitchen,howto,learn"],
      ["TuTlLenU1D0", "Fastest, cheapest way to build a deck", "deck,outdoor,howto,learn"],
      ["xBRYxYQFP9g", "Build a deck over an existing patio", "deck,outdoor,howto,learn"],
      ["09EhyopkKho", "Quick patio cover build", "deck,outdoor,howto,learn"],
      ["hMdHPBlAXb0", "Build a deck over a concrete slab", "deck,outdoor,howto,learn"],
      ["Kx0a_tR89Pg", "Quick grout repairs with grout caulk", "grout,caulk,howto,learn"],
      ["JWPRi3CREOk", "Caulk shower corners: silicone vs grout", "caulk,bathroom,tile,learn"],
      ["jvq66AyboZU", "Silicone: where to actually use it", "caulk,tile,howto,learn"],
      ["R3AA0bXfuUY", "Perfect grout lines with a tape trick", "grout,tile,howto,learn"],
      ["mjpONs0btGQ", "Caulk or grout — which & when?", "caulk,grout,learn"],
      ["fgCmHKmk-LM", "Easy concrete finishing with the right tools", "concrete,tools,learn"],
      ["9rkmkC_0rwo", "The 'funny float' concrete tool", "concrete,funny,tools"],
      ["Rou8lnTKzRo", "Perfect concrete troweling (beginners)", "concrete,howto,learn"],
      ["1WrnFx51mZk", "Perfect concrete broom finish", "concrete,howto,learn"],
      ["Utw1zDwkUXI", "Concrete garage floor finish", "concrete,flooring,learn"],
      ["5J46rDg4GLI", "Installing kitchen countertops: the guide", "countertop,kitchen,howto,learn"],
      ["I0D7__7ZuU0", "Secure countertop joining with a J-hook", "countertop,kitchen,howto,learn"],
      ["Z3Lu6q4imgA", "How long countertop installs take", "countertop,kitchen,learn"],
      ["SgBooIToKN0", "Install granite seam countertops", "countertop,kitchen,howto,learn"],
      ["toQXGo7k4hM", "Waterproof basement walls with paint", "basement,waterproofing,howto,learn"],
      ["Jh7i1c2DwHM", "Top basement waterproofing techniques", "basement,waterproofing,howto,learn"],
      ["DjZvcFVDuzo", "Install metal frames for steel-stud walls", "framing,construction,howto,learn"],
      ["rnRqlGLpLB8", "Pro wall-framing tip", "framing,construction,howto,learn"],
      ["K2N8VW0rbx0", "Spray foam + fiberglass batt insulation", "insulation,howto,learn"],
      ["hW64oMx_oaA", "DIY spray foam insulation", "insulation,diy,learn"],
      ["tM7KkjZ7iWU", "How to install most light fixtures", "electrical,lighting,howto,learn"],
      ["miOU7r40A6w", "Install a pendant light (step by step)", "electrical,lighting,howto,learn"],
      ["sKu3QjT-OAE", "Install an old-work electrical box", "electrical,howto,learn"],
      ["gnjoKrx47mE", "Better curb appeal: siding details", "exterior,siding,howto,learn"],
      ["ixoX5LpLT9Q", "Combine siding materials for a modern look", "exterior,siding,howto,learn"],
      ["yv1FYFAY0mQ", "How to improve your curb appeal", "exterior,curb-appeal,learn"],
      ["3E60B-9hTcw", "Streamline baseboard install with adhesive", "trim,baseboard,howto,learn"],
      ["Sa87IcyUxKY", "Install a pre-hung interior door (basics)", "doors,carpentry,howto,learn"],
      ["bvtD4HWk3Xc", "How a pro installs a pre-hung door", "doors,carpentry,howto,learn"],
      ["hkslHfqZRv8", "How to install a tile backsplash", "tile,backsplash,kitchen,howto,learn"],
      ["eFHGSlSNj9c", "Tile backsplash made approachable", "tile,backsplash,kitchen,howto,learn"],
      ["3Hex6e1TsPw", "Install a PVC subway tile backsplash", "tile,backsplash,howto,learn"],
      ["oznXzlQD4mI", "How to tile a backsplash", "tile,backsplash,kitchen,howto,learn"],
      ["-70yd0Z_S5M", "Install interlocking pavers like a pro (GTA)", "interlock,paver,outdoor,howto,learn"],
      ["fPJKQ12EQnY", "Install a tilt-sash window screen", "windows,howto,learn"],
      ["mdmLj0ng_hs", "Window install with a winch hoist", "windows,diy"],
      ["EnRcVZ4NJM8", "Find vinyl window install screws", "windows,howto,learn"],
      ["kuN7h6-i9hY", "How to install a window", "windows,howto,learn"],
      ["VqegTxICjMI", "DIY shiplap accent wall", "accent-wall,carpentry,howto,learn"],
      ["QM9udTCgCTA", "Epic DIY garage floor transformation", "epoxy,flooring,transformation"],
      ["S4AmMiELXrU", "Epoxy-coat your garage floor", "epoxy,flooring,howto,learn"],
      ["El2XdLnvbk4", "Demolition day on my house", "demolition,renovation"],
      ["k71zynO0kQw", "Extreme demolition surprise", "demolition,renovation"],
      ["mV_FXH1GLko", "That blade ended those stairs 😭", "demolition,funny"],
      ["QB2j-Vg8M2U", "Break rock silently with Dynacem", "demolition,concrete,learn"],
      ["Xj8t8Z6MiEI", "How to install a fence gate", "fence,outdoor,howto,learn"],
      ["R-prCd1GNyI", "How to set a fence post", "fence,outdoor,howto,learn"],
      ["N8GKuAsh_dE", "Build a cheap garden fence", "fence,outdoor,diy,learn"],
      ["fBd_z_iR8WM", "DIY vinyl fence — no cutting", "fence,outdoor,howto,learn"],
      ["wT1lljNZkMU", "Front-yard walkway: block & stone path", "outdoor,landscaping,howto,learn"],
      ["QRT0J1pvQwA", "Easiest 3-step gutter cleaning", "gutters,maintenance,howto,learn"],
      ["qJFfWDP9owQ", "Safe, simple gutter cleaning", "gutters,maintenance,howto,learn"],
      ["9qIsjU1s4a4", "Install a new bathroom vanity", "vanity,bathroom,howto,learn"],
      ["iAhoTXq0gVE", "Unlevel bathroom vanity? Fix it", "vanity,bathroom,howto,learn"],
      ["GRWEbry8nlM", "Install a push-to-stop vanity drain", "vanity,plumbing,howto,learn"],
      ["0VoW1A9nCAo", "Satisfying driveway pressure wash", "pressure-washing,outdoor,satisfying"],
      ["xuz0PALJRsU", "The soft-wash revolution", "pressure-washing,satisfying"],
      ["_bzfBlCmQbo", "$400 pressure-washing transformation", "pressure-washing,transformation"],
      ["WIwYrbMewXc", "Update your stair railing", "staircase,railing,howto,learn"],
      ["lxd9nuYLFko", "Popcorn ceiling removal, the easy way", "ceiling,demolition,howto,learn"],
      ["rCrMDPzAFuI", "Peel & stick wallpaper made easy", "wallpaper,howto,learn"],
      ["NsDAE1YgJJE", "Peel & stick wallpaper on textured walls", "wallpaper,howto,learn"],
      ["0-7jaQC6utM", "Install a mantel shelf (easy DIY)", "fireplace,mantel,carpentry,howto,learn"],
      ["zuIkV_dM2mA", "French-cleat mantel install", "fireplace,mantel,carpentry,howto,learn"],
      ["43hL_sRc-wI", "DIY custom closet makeover", "closet,storage,howto,learn"],
      ["U0KifUW_2Wk", "Simple shelving for small closets", "closet,storage,carpentry,learn"],
      ["JHMQooMWl9M", "Build a built-in closet from scratch", "closet,carpentry,howto,learn"],
      ["t5MRbXH3Clg", "How to patch a wall (DIY basics)", "drywall,patch,howto,learn"],
      ["Whok4KY9hds", "Build a fluted kitchen island", "kitchen,island,carpentry,howto,learn"],
      ["SgHDBq8gL9I", "Build a kitchen island the easy way", "kitchen,island,carpentry,howto,learn"],
      ["-N-v9T1eCFA", "Curved kitchen island build", "kitchen,island,carpentry,learn"],
      ["HzW9jYJaIZc", "DIY kitchen island ✨", "kitchen,island,diy,learn"],
      ["bfWnegYRCgM", "DIY 12x12 she-shed plans", "shed,outdoor,build,learn"],
      ["nBwv6Lb3xgc", "Build a DIY tiny house / she-shed", "shed,outdoor,build,learn"],
      ["WmFco3CNyJU", "Install a Matter smart switch", "smart-home,electrical,howto,learn"],
      ["uV_Yc6DF6qk", "DIY smart-home security install", "smart-home,security,howto,learn"],
      ["1bNGhdzzZw4", "Install a Google Nest thermostat", "smart-home,hvac,howto,learn"],
      ["ebPcojMsL5I", "Replace a bathroom faucet", "plumbing,bathroom,howto,learn"],
    ].freeze

    def self.run!
      return if ::PluginStore.get(::DiscourseShorts::PLUGIN_NAME, "seeded_v1")
      STARTER.each do |vid, title, tags|
        next if ::DiscourseShorts::Short.exists?(video_id: vid)
        begin
          ::DiscourseShorts::Short.create!(
            video_id: vid, provider: "youtube", title: title, tags: tags,
            status: "approved", source: "seed"
          )
        rescue StandardError => e
          Rails.logger.warn("[discourse-shorts] seed #{vid}: #{e.class} #{e.message}")
        end
      end
      ::PluginStore.set(::DiscourseShorts::PLUGIN_NAME, "seeded_v1", true)
    rescue StandardError => e
      Rails.logger.warn("[discourse-shorts] seeder failed: #{e.class} #{e.message}")
    end
  end
end
